"""added a species to animal

Revision ID: 123e497756f7
Revises: ba95b33f91a9
Create Date: 2025-06-25 12:52:18.305342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123e497756f7'
down_revision = 'ba95b33f91a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('species',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('species',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
