"""Initial migration.

Revision ID: 5e5cef638400
Revises: 
Create Date: 2025-06-24 11:34:58.613157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5cef638400'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('health_status', sa.String(), nullable=False),
    sa.Column('adoption_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal'))
    )
    op.create_table('staffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staffs')),
    sa.UniqueConstraint('contact_info', name=op.f('uq_staffs_contact_info')),
    sa.UniqueConstraint('email', name=op.f('uq_staffs_email'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('contact_info', name=op.f('uq_users_contact_info')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('adoptionrequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_adoptionrequests_animal_id_animal')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_adoptionrequests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adoptionrequests'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adoptionrequests')
    op.drop_table('users')
    op.drop_table('staffs')
    op.drop_table('animal')
    # ### end Alembic commands ###
